// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockBroadcaster is an autogenerated mock type for the Broadcaster type
type MockBroadcaster struct {
	mock.Mock
}

type MockBroadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroadcaster) EXPECT() *MockBroadcaster_Expecter {
	return &MockBroadcaster_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function with given fields: _a0
func (_m *MockBroadcaster) Broadcast(_a0 []byte) {
	_m.Called(_a0)
}

// MockBroadcaster_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockBroadcaster_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - _a0 []byte
func (_e *MockBroadcaster_Expecter) Broadcast(_a0 interface{}) *MockBroadcaster_Broadcast_Call {
	return &MockBroadcaster_Broadcast_Call{Call: _e.mock.On("Broadcast", _a0)}
}

func (_c *MockBroadcaster_Broadcast_Call) Run(run func(_a0 []byte)) *MockBroadcaster_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockBroadcaster_Broadcast_Call) Return() *MockBroadcaster_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBroadcaster_Broadcast_Call) RunAndReturn(run func([]byte)) *MockBroadcaster_Broadcast_Call {
	_c.Run(run)
	return _c
}

// NewMockBroadcaster creates a new instance of MockBroadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroadcaster {
	mock := &MockBroadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
