// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	events "github.com/manaraph/stream-aggregator/pkg/events"

	streamv1 "github.com/manaraph/stream-aggregator/pkg/pb/stream/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher struct {
	mock.Mock
}

type MockDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatcher) EXPECT() *MockDispatcher_Expecter {
	return &MockDispatcher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: _a0
func (_m *MockDispatcher) Publish(_a0 events.Message) {
	_m.Called(_a0)
}

// MockDispatcher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockDispatcher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - _a0 events.Message
func (_e *MockDispatcher_Expecter) Publish(_a0 interface{}) *MockDispatcher_Publish_Call {
	return &MockDispatcher_Publish_Call{Call: _e.mock.On("Publish", _a0)}
}

func (_c *MockDispatcher_Publish_Call) Run(run func(_a0 events.Message)) *MockDispatcher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(events.Message))
	})
	return _c
}

func (_c *MockDispatcher_Publish_Call) Return() *MockDispatcher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_Publish_Call) RunAndReturn(run func(events.Message)) *MockDispatcher_Publish_Call {
	_c.Run(run)
	return _c
}

// PublishMetrics provides a mock function with given fields: _a0
func (_m *MockDispatcher) PublishMetrics(_a0 *streamv1.IngestMetricsRequest) {
	_m.Called(_a0)
}

// MockDispatcher_PublishMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMetrics'
type MockDispatcher_PublishMetrics_Call struct {
	*mock.Call
}

// PublishMetrics is a helper method to define mock.On call
//   - _a0 *streamv1.IngestMetricsRequest
func (_e *MockDispatcher_Expecter) PublishMetrics(_a0 interface{}) *MockDispatcher_PublishMetrics_Call {
	return &MockDispatcher_PublishMetrics_Call{Call: _e.mock.On("PublishMetrics", _a0)}
}

func (_c *MockDispatcher_PublishMetrics_Call) Run(run func(_a0 *streamv1.IngestMetricsRequest)) *MockDispatcher_PublishMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*streamv1.IngestMetricsRequest))
	})
	return _c
}

func (_c *MockDispatcher_PublishMetrics_Call) Return() *MockDispatcher_PublishMetrics_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatcher_PublishMetrics_Call) RunAndReturn(run func(*streamv1.IngestMetricsRequest)) *MockDispatcher_PublishMetrics_Call {
	_c.Run(run)
	return _c
}

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher {
	mock := &MockDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
