// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mqtt "github.com/eclipse/paho.mqtt.golang"
	mock "github.com/stretchr/testify/mock"
)

// MockBroker is an autogenerated mock type for the Broker type
type MockBroker struct {
	mock.Mock
}

type MockBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBroker) EXPECT() *MockBroker_Expecter {
	return &MockBroker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockBroker) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBroker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockBroker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockBroker_Expecter) Close() *MockBroker_Close_Call {
	return &MockBroker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockBroker_Close_Call) Run(run func()) *MockBroker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBroker_Close_Call) Return(_a0 error) *MockBroker_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBroker_Close_Call) RunAndReturn(run func() error) *MockBroker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: topic, data
func (_m *MockBroker) Publish(topic string, data []byte) error {
	ret := _m.Called(topic, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(topic, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - topic string
//   - data []byte
func (_e *MockBroker_Expecter) Publish(topic interface{}, data interface{}) *MockBroker_Publish_Call {
	return &MockBroker_Publish_Call{Call: _e.mock.On("Publish", topic, data)}
}

func (_c *MockBroker_Publish_Call) Run(run func(topic string, data []byte)) *MockBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockBroker_Publish_Call) Return(_a0 error) *MockBroker_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBroker_Publish_Call) RunAndReturn(run func(string, []byte) error) *MockBroker_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: topic, handler
func (_m *MockBroker) Subscribe(topic string, handler func(mqtt.Client, mqtt.Message)) error {
	ret := _m.Called(topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(mqtt.Client, mqtt.Message)) error); ok {
		r0 = rf(topic, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBroker_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBroker_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic string
//   - handler func(mqtt.Client , mqtt.Message)
func (_e *MockBroker_Expecter) Subscribe(topic interface{}, handler interface{}) *MockBroker_Subscribe_Call {
	return &MockBroker_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, handler)}
}

func (_c *MockBroker_Subscribe_Call) Run(run func(topic string, handler func(mqtt.Client, mqtt.Message))) *MockBroker_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(mqtt.Client, mqtt.Message)))
	})
	return _c
}

func (_c *MockBroker_Subscribe_Call) Return(_a0 error) *MockBroker_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBroker_Subscribe_Call) RunAndReturn(run func(string, func(mqtt.Client, mqtt.Message)) error) *MockBroker_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBroker creates a new instance of MockBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBroker {
	mock := &MockBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
