services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - '1883:1883'
    networks:
      - app-network
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    healthcheck:
      test: ['CMD', 'mosquitto_sub', '-h', 'localhost', '-t', 'test', '-C', '1']
      interval: 5s
      retries: 5
      start_period: 5s

  gateway:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.gateway
    container_name: gateway-service
    ports:
      - '8080:8080'
      - '50051:50051'
    environment:
      - GRPC_PORT
      - HTTP_PORT
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 50051 || exit 1']
      interval: 5s
      retries: 5
      start_period: 5s

  generator:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.generator
    container_name: generator-service
    depends_on:
      - mosquitto
    networks:
      - app-network
    environment:
      - MQTT_BROKER
      - GENERATOR_ID
      - PUBLISH_RATE

  ingestion:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.ingestion
    container_name: ingestion-service
    depends_on:
      - mosquitto
      - gateway
    environment:
      - MQTT_BROKER
      - INGESTION_ID
      - GATEWAY_ADDR
      - INGESTION_WORKERS
      - INGESTION_QUEUE_SIZE
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
