version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  generator:
    build: ./generator
    depends_on:
      - mosquitto

  ingestion:
    build: ./ingestion
    environment:
      - MQTT_BROKER=tcp://mosquitto:1883
    depends_on:
      - mosquitto
