FROM golang:1.24-alpine AS builder
WORKDIR /app
ENV GO111MODULE=on

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o /bin/ingestion ./cmd/ingestion

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /bin/ingestion /bin/ingestion
ENTRYPOINT ["/bin/ingestion"]
