// Code generated by mockery v2.53.5. DO NOT EDIT.

package ingestion

import (
	context "context"

	domain "github.com/manaraph/stream-aggregator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSensorStore is an autogenerated mock type for the sensorStore type
type MockSensorStore struct {
	mock.Mock
}

type MockSensorStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorStore) EXPECT() *MockSensorStore_Expecter {
	return &MockSensorStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockSensorStore) Close() {
	_m.Called()
}

// MockSensorStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSensorStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSensorStore_Expecter) Close() *MockSensorStore_Close_Call {
	return &MockSensorStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSensorStore_Close_Call) Run(run func()) *MockSensorStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSensorStore_Close_Call) Return() *MockSensorStore_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSensorStore_Close_Call) RunAndReturn(run func()) *MockSensorStore_Close_Call {
	_c.Run(run)
	return _c
}

// InsertBatch provides a mock function with given fields: _a0, _a1
func (_m *MockSensorStore) InsertBatch(_a0 context.Context, _a1 []domain.Sensor) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Sensor) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSensorStore_InsertBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertBatch'
type MockSensorStore_InsertBatch_Call struct {
	*mock.Call
}

// InsertBatch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []domain.Sensor
func (_e *MockSensorStore_Expecter) InsertBatch(_a0 interface{}, _a1 interface{}) *MockSensorStore_InsertBatch_Call {
	return &MockSensorStore_InsertBatch_Call{Call: _e.mock.On("InsertBatch", _a0, _a1)}
}

func (_c *MockSensorStore_InsertBatch_Call) Run(run func(_a0 context.Context, _a1 []domain.Sensor)) *MockSensorStore_InsertBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Sensor))
	})
	return _c
}

func (_c *MockSensorStore_InsertBatch_Call) Return(_a0 error) *MockSensorStore_InsertBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSensorStore_InsertBatch_Call) RunAndReturn(run func(context.Context, []domain.Sensor) error) *MockSensorStore_InsertBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSensorStore creates a new instance of MockSensorStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensorStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensorStore {
	mock := &MockSensorStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
