// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stream/v1/metrics.proto

package streamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processed     uint64                 `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
	Dropped       uint64                 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	Used          uint32                 `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Capacity      uint32                 `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxUsed       uint32                 `protobuf:"varint,5,opt,name=max_used,json=maxUsed,proto3" json:"max_used,omitempty"`
	Utilization   float64                `protobuf:"fixed64,6,opt,name=utilization,proto3" json:"utilization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMetrics) Reset() {
	*x = QueueMetrics{}
	mi := &file_stream_v1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetrics) ProtoMessage() {}

func (x *QueueMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetrics.ProtoReflect.Descriptor instead.
func (*QueueMetrics) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMetrics) GetProcessed() uint64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *QueueMetrics) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *QueueMetrics) GetUsed() uint32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *QueueMetrics) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *QueueMetrics) GetMaxUsed() uint32 {
	if x != nil {
		return x.MaxUsed
	}
	return 0
}

func (x *QueueMetrics) GetUtilization() float64 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

type ThroughputMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublishRate   float64                `protobuf:"fixed64,1,opt,name=publish_rate,json=publishRate,proto3" json:"publish_rate,omitempty"`
	IngestionRate float64                `protobuf:"fixed64,2,opt,name=ingestion_rate,json=ingestionRate,proto3" json:"ingestion_rate,omitempty"`
	GrpcRate      float64                `protobuf:"fixed64,3,opt,name=grpc_rate,json=grpcRate,proto3" json:"grpc_rate,omitempty"`
	WebsocketRate float64                `protobuf:"fixed64,4,opt,name=websocket_rate,json=websocketRate,proto3" json:"websocket_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThroughputMetrics) Reset() {
	*x = ThroughputMetrics{}
	mi := &file_stream_v1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThroughputMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThroughputMetrics) ProtoMessage() {}

func (x *ThroughputMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThroughputMetrics.ProtoReflect.Descriptor instead.
func (*ThroughputMetrics) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *ThroughputMetrics) GetPublishRate() float64 {
	if x != nil {
		return x.PublishRate
	}
	return 0
}

func (x *ThroughputMetrics) GetIngestionRate() float64 {
	if x != nil {
		return x.IngestionRate
	}
	return 0
}

func (x *ThroughputMetrics) GetGrpcRate() float64 {
	if x != nil {
		return x.GrpcRate
	}
	return 0
}

func (x *ThroughputMetrics) GetWebsocketRate() float64 {
	if x != nil {
		return x.WebsocketRate
	}
	return 0
}

type LatencyMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AverageMs     uint32                 `protobuf:"varint,1,opt,name=average_ms,json=averageMs,proto3" json:"average_ms,omitempty"`
	P95Ms         uint32                 `protobuf:"varint,2,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	MaxMs         uint32                 `protobuf:"varint,3,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyMetrics) Reset() {
	*x = LatencyMetrics{}
	mi := &file_stream_v1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyMetrics) ProtoMessage() {}

func (x *LatencyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyMetrics.ProtoReflect.Descriptor instead.
func (*LatencyMetrics) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *LatencyMetrics) GetAverageMs() uint32 {
	if x != nil {
		return x.AverageMs
	}
	return 0
}

func (x *LatencyMetrics) GetP95Ms() uint32 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *LatencyMetrics) GetMaxMs() uint32 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

type ConnectionMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Reconnects    uint32                 `protobuf:"varint,2,opt,name=reconnects,proto3" json:"reconnects,omitempty"`
	Errors        uint32                 `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMetrics) Reset() {
	*x = ConnectionMetrics{}
	mi := &file_stream_v1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMetrics) ProtoMessage() {}

func (x *ConnectionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMetrics.ProtoReflect.Descriptor instead.
func (*ConnectionMetrics) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionMetrics) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectionMetrics) GetReconnects() uint32 {
	if x != nil {
		return x.Reconnects
	}
	return 0
}

func (x *ConnectionMetrics) GetErrors() uint32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

type RuntimeMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds    uint64                 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Goroutines       uint32                 `protobuf:"varint,2,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	MemoryBytes      uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	WebsocketClients uint32                 `protobuf:"varint,4,opt,name=websocket_clients,json=websocketClients,proto3" json:"websocket_clients,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeMetrics) Reset() {
	*x = RuntimeMetrics{}
	mi := &file_stream_v1_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeMetrics) ProtoMessage() {}

func (x *RuntimeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeMetrics.ProtoReflect.Descriptor instead.
func (*RuntimeMetrics) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeMetrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *RuntimeMetrics) GetGoroutines() uint32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *RuntimeMetrics) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RuntimeMetrics) GetWebsocketClients() uint32 {
	if x != nil {
		return x.WebsocketClients
	}
	return 0
}

type IngestMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *QueueMetrics          `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Throughput    *ThroughputMetrics     `protobuf:"bytes,2,opt,name=throughput,proto3" json:"throughput,omitempty"`
	Latency       *LatencyMetrics        `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Grpc          *ConnectionMetrics     `protobuf:"bytes,4,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Broker        *ConnectionMetrics     `protobuf:"bytes,5,opt,name=broker,proto3" json:"broker,omitempty"`
	Runtime       *RuntimeMetrics        `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMetricsRequest) Reset() {
	*x = IngestMetricsRequest{}
	mi := &file_stream_v1_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMetricsRequest) ProtoMessage() {}

func (x *IngestMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMetricsRequest.ProtoReflect.Descriptor instead.
func (*IngestMetricsRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *IngestMetricsRequest) GetQueue() *QueueMetrics {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *IngestMetricsRequest) GetThroughput() *ThroughputMetrics {
	if x != nil {
		return x.Throughput
	}
	return nil
}

func (x *IngestMetricsRequest) GetLatency() *LatencyMetrics {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *IngestMetricsRequest) GetGrpc() *ConnectionMetrics {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *IngestMetricsRequest) GetBroker() *ConnectionMetrics {
	if x != nil {
		return x.Broker
	}
	return nil
}

func (x *IngestMetricsRequest) GetRuntime() *RuntimeMetrics {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type IngestMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestMetricsResponse) Reset() {
	*x = IngestMetricsResponse{}
	mi := &file_stream_v1_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestMetricsResponse) ProtoMessage() {}

func (x *IngestMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestMetricsResponse.ProtoReflect.Descriptor instead.
func (*IngestMetricsResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_metrics_proto_rawDescGZIP(), []int{6}
}

var File_stream_v1_metrics_proto protoreflect.FileDescriptor

const file_stream_v1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17stream/v1/metrics.proto\x12\tstream.v1\"\xb3\x01\n" +
	"\fQueueMetrics\x12\x1c\n" +
	"\tprocessed\x18\x01 \x01(\x04R\tprocessed\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x04R\adropped\x12\x12\n" +
	"\x04used\x18\x03 \x01(\rR\x04used\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\rR\bcapacity\x12\x19\n" +
	"\bmax_used\x18\x05 \x01(\rR\amaxUsed\x12 \n" +
	"\vutilization\x18\x06 \x01(\x01R\vutilization\"\xa1\x01\n" +
	"\x11ThroughputMetrics\x12!\n" +
	"\fpublish_rate\x18\x01 \x01(\x01R\vpublishRate\x12%\n" +
	"\x0eingestion_rate\x18\x02 \x01(\x01R\ringestionRate\x12\x1b\n" +
	"\tgrpc_rate\x18\x03 \x01(\x01R\bgrpcRate\x12%\n" +
	"\x0ewebsocket_rate\x18\x04 \x01(\x01R\rwebsocketRate\"]\n" +
	"\x0eLatencyMetrics\x12\x1d\n" +
	"\n" +
	"average_ms\x18\x01 \x01(\rR\taverageMs\x12\x15\n" +
	"\x06p95_ms\x18\x02 \x01(\rR\x05p95Ms\x12\x15\n" +
	"\x06max_ms\x18\x03 \x01(\rR\x05maxMs\"i\n" +
	"\x11ConnectionMetrics\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1e\n" +
	"\n" +
	"reconnects\x18\x02 \x01(\rR\n" +
	"reconnects\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\rR\x06errors\"\xa7\x01\n" +
	"\x0eRuntimeMetrics\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x04R\ruptimeSeconds\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x02 \x01(\rR\n" +
	"goroutines\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12+\n" +
	"\x11websocket_clients\x18\x04 \x01(\rR\x10websocketClients\"\xd5\x02\n" +
	"\x14IngestMetricsRequest\x12-\n" +
	"\x05queue\x18\x01 \x01(\v2\x17.stream.v1.QueueMetricsR\x05queue\x12<\n" +
	"\n" +
	"throughput\x18\x02 \x01(\v2\x1c.stream.v1.ThroughputMetricsR\n" +
	"throughput\x123\n" +
	"\alatency\x18\x03 \x01(\v2\x19.stream.v1.LatencyMetricsR\alatency\x120\n" +
	"\x04grpc\x18\x04 \x01(\v2\x1c.stream.v1.ConnectionMetricsR\x04grpc\x124\n" +
	"\x06broker\x18\x05 \x01(\v2\x1c.stream.v1.ConnectionMetricsR\x06broker\x123\n" +
	"\aruntime\x18\x06 \x01(\v2\x19.stream.v1.RuntimeMetricsR\aruntime\"\x17\n" +
	"\x15IngestMetricsResponse2f\n" +
	"\x0eMetricsService\x12T\n" +
	"\rIngestMetrics\x12\x1f.stream.v1.IngestMetricsRequest\x1a .stream.v1.IngestMetricsResponse(\x01BAZ?github.com/manaraph/stream-aggregator/pkg/pb/stream/v1;streamv1b\x06proto3"

var (
	file_stream_v1_metrics_proto_rawDescOnce sync.Once
	file_stream_v1_metrics_proto_rawDescData []byte
)

func file_stream_v1_metrics_proto_rawDescGZIP() []byte {
	file_stream_v1_metrics_proto_rawDescOnce.Do(func() {
		file_stream_v1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_metrics_proto_rawDesc), len(file_stream_v1_metrics_proto_rawDesc)))
	})
	return file_stream_v1_metrics_proto_rawDescData
}

var file_stream_v1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stream_v1_metrics_proto_goTypes = []any{
	(*QueueMetrics)(nil),          // 0: stream.v1.QueueMetrics
	(*ThroughputMetrics)(nil),     // 1: stream.v1.ThroughputMetrics
	(*LatencyMetrics)(nil),        // 2: stream.v1.LatencyMetrics
	(*ConnectionMetrics)(nil),     // 3: stream.v1.ConnectionMetrics
	(*RuntimeMetrics)(nil),        // 4: stream.v1.RuntimeMetrics
	(*IngestMetricsRequest)(nil),  // 5: stream.v1.IngestMetricsRequest
	(*IngestMetricsResponse)(nil), // 6: stream.v1.IngestMetricsResponse
}
var file_stream_v1_metrics_proto_depIdxs = []int32{
	0, // 0: stream.v1.IngestMetricsRequest.queue:type_name -> stream.v1.QueueMetrics
	1, // 1: stream.v1.IngestMetricsRequest.throughput:type_name -> stream.v1.ThroughputMetrics
	2, // 2: stream.v1.IngestMetricsRequest.latency:type_name -> stream.v1.LatencyMetrics
	3, // 3: stream.v1.IngestMetricsRequest.grpc:type_name -> stream.v1.ConnectionMetrics
	3, // 4: stream.v1.IngestMetricsRequest.broker:type_name -> stream.v1.ConnectionMetrics
	4, // 5: stream.v1.IngestMetricsRequest.runtime:type_name -> stream.v1.RuntimeMetrics
	5, // 6: stream.v1.MetricsService.IngestMetrics:input_type -> stream.v1.IngestMetricsRequest
	6, // 7: stream.v1.MetricsService.IngestMetrics:output_type -> stream.v1.IngestMetricsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_stream_v1_metrics_proto_init() }
func file_stream_v1_metrics_proto_init() {
	if File_stream_v1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_metrics_proto_rawDesc), len(file_stream_v1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_v1_metrics_proto_goTypes,
		DependencyIndexes: file_stream_v1_metrics_proto_depIdxs,
		MessageInfos:      file_stream_v1_metrics_proto_msgTypes,
	}.Build()
	File_stream_v1_metrics_proto = out.File
	file_stream_v1_metrics_proto_goTypes = nil
	file_stream_v1_metrics_proto_depIdxs = nil
}
