// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stream/v1/sensor.proto

package streamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IngestSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensor        string                 `protobuf:"bytes,1,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSensorRequest) Reset() {
	*x = IngestSensorRequest{}
	mi := &file_stream_v1_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSensorRequest) ProtoMessage() {}

func (x *IngestSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSensorRequest.ProtoReflect.Descriptor instead.
func (*IngestSensorRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *IngestSensorRequest) GetSensor() string {
	if x != nil {
		return x.Sensor
	}
	return ""
}

func (x *IngestSensorRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IngestSensorRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type IngestSensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSensorResponse) Reset() {
	*x = IngestSensorResponse{}
	mi := &file_stream_v1_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSensorResponse) ProtoMessage() {}

func (x *IngestSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSensorResponse.ProtoReflect.Descriptor instead.
func (*IngestSensorResponse) Descriptor() ([]byte, []int) {
	return file_stream_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *IngestSensorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestSensorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stream_v1_sensor_proto protoreflect.FileDescriptor

const file_stream_v1_sensor_proto_rawDesc = "" +
	"\n" +
	"\x16stream/v1/sensor.proto\x12\tstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x13IngestSensorRequest\x12\x16\n" +
	"\x06sensor\x18\x01 \x01(\tR\x06sensor\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"J\n" +
	"\x14IngestSensorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2b\n" +
	"\rSensorService\x12Q\n" +
	"\fIngestSensor\x12\x1e.stream.v1.IngestSensorRequest\x1a\x1f.stream.v1.IngestSensorResponse(\x01BAZ?github.com/manaraph/stream-aggregator/pkg/pb/stream/v1;streamv1b\x06proto3"

var (
	file_stream_v1_sensor_proto_rawDescOnce sync.Once
	file_stream_v1_sensor_proto_rawDescData []byte
)

func file_stream_v1_sensor_proto_rawDescGZIP() []byte {
	file_stream_v1_sensor_proto_rawDescOnce.Do(func() {
		file_stream_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_sensor_proto_rawDesc), len(file_stream_v1_sensor_proto_rawDesc)))
	})
	return file_stream_v1_sensor_proto_rawDescData
}

var file_stream_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_v1_sensor_proto_goTypes = []any{
	(*IngestSensorRequest)(nil),   // 0: stream.v1.IngestSensorRequest
	(*IngestSensorResponse)(nil),  // 1: stream.v1.IngestSensorResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_stream_v1_sensor_proto_depIdxs = []int32{
	2, // 0: stream.v1.IngestSensorRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: stream.v1.SensorService.IngestSensor:input_type -> stream.v1.IngestSensorRequest
	1, // 2: stream.v1.SensorService.IngestSensor:output_type -> stream.v1.IngestSensorResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stream_v1_sensor_proto_init() }
func file_stream_v1_sensor_proto_init() {
	if File_stream_v1_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_sensor_proto_rawDesc), len(file_stream_v1_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_v1_sensor_proto_goTypes,
		DependencyIndexes: file_stream_v1_sensor_proto_depIdxs,
		MessageInfos:      file_stream_v1_sensor_proto_msgTypes,
	}.Build()
	File_stream_v1_sensor_proto = out.File
	file_stream_v1_sensor_proto_goTypes = nil
	file_stream_v1_sensor_proto_depIdxs = nil
}
