// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	streamv1 "github.com/manaraph/stream-aggregator/pkg/pb/stream/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockSensorStreamClient is an autogenerated mock type for the SensorStreamClient type
type MockSensorStreamClient struct {
	mock.Mock
}

type MockSensorStreamClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorStreamClient) EXPECT() *MockSensorStreamClient_Expecter {
	return &MockSensorStreamClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0
func (_m *MockSensorStreamClient) Send(_a0 *streamv1.IngestSensorRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*streamv1.IngestSensorRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSensorStreamClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSensorStreamClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *streamv1.IngestSensorRequest
func (_e *MockSensorStreamClient_Expecter) Send(_a0 interface{}) *MockSensorStreamClient_Send_Call {
	return &MockSensorStreamClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockSensorStreamClient_Send_Call) Run(run func(_a0 *streamv1.IngestSensorRequest)) *MockSensorStreamClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*streamv1.IngestSensorRequest))
	})
	return _c
}

func (_c *MockSensorStreamClient_Send_Call) Return(_a0 error) *MockSensorStreamClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSensorStreamClient_Send_Call) RunAndReturn(run func(*streamv1.IngestSensorRequest) error) *MockSensorStreamClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSensorStreamClient creates a new instance of MockSensorStreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensorStreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensorStreamClient {
	mock := &MockSensorStreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
