// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	streamv1 "github.com/manaraph/stream-aggregator/pkg/pb/stream/v1"
	mock "github.com/stretchr/testify/mock"
)

// MockMetricsStreamClient is an autogenerated mock type for the MetricsStreamClient type
type MockMetricsStreamClient struct {
	mock.Mock
}

type MockMetricsStreamClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsStreamClient) EXPECT() *MockMetricsStreamClient_Expecter {
	return &MockMetricsStreamClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0
func (_m *MockMetricsStreamClient) Send(_a0 *streamv1.IngestMetricsRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*streamv1.IngestMetricsRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMetricsStreamClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMetricsStreamClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *streamv1.IngestMetricsRequest
func (_e *MockMetricsStreamClient_Expecter) Send(_a0 interface{}) *MockMetricsStreamClient_Send_Call {
	return &MockMetricsStreamClient_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockMetricsStreamClient_Send_Call) Run(run func(_a0 *streamv1.IngestMetricsRequest)) *MockMetricsStreamClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*streamv1.IngestMetricsRequest))
	})
	return _c
}

func (_c *MockMetricsStreamClient_Send_Call) Return(_a0 error) *MockMetricsStreamClient_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMetricsStreamClient_Send_Call) RunAndReturn(run func(*streamv1.IngestMetricsRequest) error) *MockMetricsStreamClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsStreamClient creates a new instance of MockMetricsStreamClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsStreamClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsStreamClient {
	mock := &MockMetricsStreamClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
